### ISSUE TITLE
Kanban Group Project 

### ISSUE THREAD

**Issue by peterboro** [peterboro/space-travelers-hub#25]
- Two Participants @BucurEva87 and @peterboro 
- Link https://github.com/peterboro/space-travelers-hub/projects/1

**Comment by Bondok6** [comment]
# STATUS: APPROVED :green_circle: :clap: 

## Hi Team 🙋‍♂️, 
Your kanbanboard is setup correctly!  There is nothing else to say other than... Great job 👏 

HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏
